apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-aot-demo-config
  labels:
    app: spring-aot-demo
data:
  application.properties: |
    # Server configuration
    server.port=8080

    # Actuator configuration
    management.endpoints.web.exposure.include=health,info,metrics,prometheus
    management.endpoint.health.probes.enabled=true
    management.health.livenessState.enabled=true
    management.health.readinessState.enabled=true

    # Database configuration (H2 in-memory)
    spring.datasource.url=jdbc:h2:mem:testdb
    spring.datasource.driverClassName=org.h2.Driver
    spring.datasource.username=sa
    spring.datasource.password=
    spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
    spring.jpa.hibernate.ddl-auto=create-drop
    spring.h2.console.enabled=false

    # Logging
    logging.level.root=INFO
    logging.level.io.vgrente.spring.aot.demo=DEBUG