apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vault-connection
  namespace: default
spec:
  # Vault server address
  address: http://vault.vault.svc.cluster.local:8200

  # Skip TLS verification (only for dev/testing)
  skipTLSVerify: true